# Generated by Django 5.1 on 2024-09-01 08:31

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(choices=[('abuja', 'Abuja'), ('adamawa', 'Adamawa'), ('taraba', 'Taraba'), ('kaduna', 'Kaduna'), ('lagos', 'Lagos'), ('jos', 'Jos')], max_length=100)),
                ('primary_industry', models.CharField(choices=[('Software', 'Software'), ('Finance', 'Finance'), ('Education', 'Education')], max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
